// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBazTQRkZyfNrSxf46tcjUZsHBAucOwNjk',
    appId: '1:902042089480:web:fd1a7b977592a84b11b9bd',
    messagingSenderId: '902042089480',
    projectId: 'chat-app-7527a',
    authDomain: 'chat-app-7527a.firebaseapp.com',
    storageBucket: 'chat-app-7527a.appspot.com',
    measurementId: 'G-L5NRN69BSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_w09KGERuPrQSlffmT0ZZFS8RwCQyQw0',
    appId: '1:902042089480:android:6c89f3a539b3d0e511b9bd',
    messagingSenderId: '902042089480',
    projectId: 'chat-app-7527a',
    storageBucket: 'chat-app-7527a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsoBaacevP8rnqRlJFDfPZBh2vA4lznMw',
    appId: '1:902042089480:ios:5161a06e8f549a7c11b9bd',
    messagingSenderId: '902042089480',
    projectId: 'chat-app-7527a',
    storageBucket: 'chat-app-7527a.appspot.com',
    iosClientId: '902042089480-f0nu5b4qssrqflqlclttvrpf0p84fqpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsoBaacevP8rnqRlJFDfPZBh2vA4lznMw',
    appId: '1:902042089480:ios:5161a06e8f549a7c11b9bd',
    messagingSenderId: '902042089480',
    projectId: 'chat-app-7527a',
    storageBucket: 'chat-app-7527a.appspot.com',
    iosClientId: '902042089480-f0nu5b4qssrqflqlclttvrpf0p84fqpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
